version: "2"

linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - cyclop
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - forbidigo
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godoclint
    - godot
    - godox
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - intrange
    - makezero
    - mirror
    - misspell
    - mnd
    - modernize
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - revive
    - sloglint
    - staticcheck
    - tagalign
    - testableexamples
    - testifylint
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - whitespace
  settings:
    gocritic:
      enabled-tags:
        - performance
      disabled-checks:
        - hugeParam
    govet:
      enable:
        - shadow
    goconst:
      ignore-string-values:
        - "false"
    misspell:
      locale: US
    perfsprint:
      strconcat: false
    revive:
      rules:
        - name: unused-parameter
          disabled: true
    unused:
      field-writes-are-uses: false
      post-statements-are-reads: true
      exported-fields-are-used: false
      local-variables-are-used: false
      generated-is-used: false

formatters:
  enable:
    - gofumpt
    - goimports
